name:
services:
  db:
    container_name:
    image:
    environment:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    ports:
      -
    volumes:
      -

volumes:
  mysql_data: