DROP TABLE IF EXISTS slot_histories;
DROP TABLE IF EXISTS parking_sessions;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS gates;
DROP TABLE IF EXISTS rfid_cards;
DROP TABLE IF EXISTS parking_slots;
DROP TABLE IF EXISTS iot_devices;
DROP TABLE IF EXISTS parking_lots;
DROP TABLE IF EXISTS users;