// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Đăng nhập bằng email và mật khẩu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Đăng nhập",
                "parameters": [
                    {
                        "description": "Thông tin đăng nhập",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Đăng xuất tài khoản hiện tại và xóa refresh token cookie",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Đăng xuất",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/refresh-token": {
            "post": {
                "description": "Cấp lại access token từ refresh token trong cookie",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Làm mới access token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Tạo tài khoản mới và gửi email xác thực",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Đăng ký tài khoản",
                "parameters": [
                    {
                        "description": "Thông tin đăng ký",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/resend": {
            "post": {
                "description": "Gửi lại email xác thực tài khoản",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Gửi lại email xác thực",
                "parameters": [
                    {
                        "description": "Email người dùng",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.EmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/reset-password": {
            "patch": {
                "description": "Đặt lại mật khẩu bằng mã xác thực hoặc token reset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Đặt lại mật khẩu",
                "parameters": [
                    {
                        "description": "Thông tin đặt lại mật khẩu",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.ResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/send-reset-password": {
            "post": {
                "description": "Gửi email chứa hướng dẫn hoặc mã để đặt lại mật khẩu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Gửi email đặt lại mật khẩu",
                "parameters": [
                    {
                        "description": "Email người dùng",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.EmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/verify": {
            "get": {
                "description": "Xác thực tài khoản bằng email và mã code từ link gửi qua email",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Xác thực email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Mã xác thực",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "HTML verified page",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/gates": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gate"
                ],
                "summary": "Tạo cổng mới",
                "parameters": [
                    {
                        "description": "Thông tin cổng",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gate.CreateGateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/gates/{gateId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gate"
                ],
                "summary": "Lấy thông tin cổng theo ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID cổng",
                        "name": "gateId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gate"
                ],
                "summary": "Cập nhật thông tin cổng",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID cổng",
                        "name": "gateId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Thông tin cập nhật",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gate.UpdateGateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gate"
                ],
                "summary": "Xoá cổng",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID cổng",
                        "name": "gateId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/iot-devices": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Tạo mới một thiết bị IoT trong hệ thống",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iot_device"
                ],
                "summary": "Tạo thiết bị IoT",
                "parameters": [
                    {
                        "description": "Thông tin thiết bị IoT",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/iot_device.CreateIoTDeviceRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/iot/camera": {
            "post": {
                "description": "Lưu biển số tạm thời theo gate để chờ RFID scan consume",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iot"
                ],
                "summary": "Camera AI gửi biển số",
                "parameters": [
                    {
                        "description": "Dữ liệu từ camera",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/iot_gateway.CameraPlateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/iot_gateway.CameraPlateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/iot/rfid": {
            "post": {
                "description": "Xử lý sự kiện quẹt thẻ từ ESP32+RC522, quyết định mở/đóng barie",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iot"
                ],
                "summary": "ESP32 quẹt thẻ RFID",
                "parameters": [
                    {
                        "description": "Dữ liệu từ ESP32",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/iot_gateway.RfidScanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/iot_gateway.RfidScanResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/parking-lots": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Trả về toàn bộ danh sách bãi đỗ xe",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parking_lot"
                ],
                "summary": "Lấy danh sách bãi đỗ xe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Tạo mới một bãi đỗ xe trong hệ thống",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parking_lot"
                ],
                "summary": "Tạo bãi đỗ xe",
                "parameters": [
                    {
                        "description": "Thông tin bãi đỗ xe",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/parking_lot.CreateParkingLotRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/parking-lots/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lấy thông tin chi tiết của một bãi đỗ xe theo ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parking_lot"
                ],
                "summary": "Lấy chi tiết bãi đỗ xe",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID bãi đỗ xe",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cập nhật thông tin bãi đỗ xe theo ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parking_lot"
                ],
                "summary": "Cập nhật bãi đỗ xe",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID bãi đỗ xe",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Thông tin cập nhật bãi đỗ xe",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/parking_lot.UpdateParkingLotRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/parking-lots/{id}/gates": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parking_lot"
                ],
                "summary": "Lấy danh sách cổng theo bãi đỗ",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID bãi đỗ xe",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/parking-sessions": {
            "get": {
                "description": "Trả về danh sách tất cả phiên gửi xe",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parking_session"
                ],
                "summary": "Lấy danh sách phiên gửi xe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/parking-sessions/card/{uid}": {
            "delete": {
                "description": "Đóng phiên gửi xe đang active theo UID thẻ, dùng cho testing",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parking_session"
                ],
                "summary": "Đóng phiên gửi xe theo UID thẻ (test)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UID thẻ",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/parking-sessions/purge/{id}": {
            "delete": {
                "description": "Xóa vĩnh viễn phiên gửi xe khỏi DB",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parking_session"
                ],
                "summary": "Xóa vĩnh viễn phiên gửi xe",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID phiên gửi xe",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/parking-sessions/{id}": {
            "get": {
                "description": "Lấy thông tin phiên gửi xe theo ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parking_session"
                ],
                "summary": "Lấy chi tiết phiên gửi xe",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID phiên gửi xe",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "Đóng phiên gửi xe theo ID, dùng cho testing",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parking_session"
                ],
                "summary": "Đóng phiên gửi xe theo ID (test)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID phiên gửi xe",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/parking-slots": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Tạo mới một vị trí đỗ xe trong hệ thống",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parking_slot"
                ],
                "summary": "Tạo vị trí đỗ xe",
                "parameters": [
                    {
                        "description": "Thông tin vị trí đỗ xe",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/parking_slot.CreateParkingSlotRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/parking-slots/admin/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cập nhật trạng thái vị trí đỗ xe theo ID bởi quản trị viên hoặc quản lý",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parking_slot"
                ],
                "summary": "Quản trị viên cập nhật trạng thái vị trí đỗ",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID vị trí đỗ xe",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Thông tin cập nhật trạng thái",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/parking_slot.AdminUpdateParkingSlotRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/parking-slots/sensor": {
            "post": {
                "description": "Cập nhật trạng thái vị trí đỗ xe từ cảm biến hoặc thiết bị IoT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parking_slot"
                ],
                "summary": "Thiết bị cảm biến cập nhật trạng thái vị trí đỗ",
                "parameters": [
                    {
                        "description": "Dữ liệu trạng thái từ cảm biến",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/parking_slot.SensorUpdateParkingSlotRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/parking-slots/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lấy thông tin chi tiết của một vị trí đỗ xe theo ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parking_slot"
                ],
                "summary": "Lấy chi tiết vị trí đỗ xe",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID vị trí đỗ xe",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/parking-slots/{id}/device": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cập nhật hoặc thay đổi thiết bị IoT gắn với vị trí đỗ xe theo ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parking_slot"
                ],
                "summary": "Đổi thiết bị cho vị trí đỗ",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID vị trí đỗ xe",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Thông tin thiết bị mới",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/parking_slot.ChangeSlotDeviceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/rfid-cards": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Tạo mới thẻ RFID trong hệ thống",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rfid_card"
                ],
                "summary": "Tạo thẻ RFID",
                "parameters": [
                    {
                        "description": "Thông tin thẻ RFID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rfid_card.CreateRfidCardRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/rfid-cards/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cập nhật thông tin thẻ RFID theo ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rfid_card"
                ],
                "summary": "Cập nhật thẻ RFID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID thẻ RFID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Thông tin cập nhật",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rfid_card.UpdateRfidCardRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/slot-histories/{slotId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Trả về lịch sử hoạt động của một vị trí đỗ xe theo slot ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "slot_history"
                ],
                "summary": "Lấy lịch sử theo vị trí đỗ",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID vị trí đỗ xe",
                        "name": "slotId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lấy danh sách người dùng có phân trang và tìm kiếm",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Lấy danh sách người dùng",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Trang hiện tại",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Số lượng mỗi trang",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Từ khóa tìm kiếm",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Tạo mới người dùng bởi quản trị viên",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Admin tạo người dùng",
                "parameters": [
                    {
                        "description": "Thông tin người dùng",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/change-password": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Người dùng hiện tại đổi mật khẩu của chính mình",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Đổi mật khẩu",
                "parameters": [
                    {
                        "description": "Thông tin đổi mật khẩu",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/change-role/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Quản trị viên đổi vai trò của người dùng theo ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Đổi vai trò người dùng",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID người dùng",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Vai trò mới",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ChangeRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.EmailRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "auth.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "auth.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "auth.ResetPasswordRequest": {
            "type": "object",
            "required": [
                "code",
                "confirm_password",
                "email",
                "new_password"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "confirm_password": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "gate.CreateGateRequest": {
            "type": "object",
            "required": [
                "lot_id",
                "mac_address",
                "name",
                "type"
            ],
            "properties": {
                "lot_id": {
                    "type": "integer"
                },
                "mac_address": {
                    "type": "string",
                    "maxLength": 50
                },
                "name": {
                    "type": "string",
                    "maxLength": 50
                },
                "type": {
                    "enum": [
                        "ENTRY",
                        "EXIT"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/gate.GateType"
                        }
                    ]
                }
            }
        },
        "gate.GateType": {
            "type": "string",
            "enum": [
                "ENTRY",
                "EXIT"
            ],
            "x-enum-varnames": [
                "GateTypeEntry",
                "GateTypeExit"
            ]
        },
        "gate.UpdateGateRequest": {
            "type": "object",
            "properties": {
                "is_active": {
                    "type": "boolean"
                },
                "mac_address": {
                    "type": "string",
                    "maxLength": 50
                },
                "name": {
                    "type": "string",
                    "maxLength": 50
                },
                "type": {
                    "enum": [
                        "ENTRY",
                        "EXIT"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/gate.GateType"
                        }
                    ]
                }
            }
        },
        "iot_device.CreateIoTDeviceRequest": {
            "type": "object",
            "required": [
                "device_name",
                "mac_address"
            ],
            "properties": {
                "device_name": {
                    "type": "string"
                },
                "lot_id": {
                    "type": "integer"
                },
                "mac_address": {
                    "type": "string"
                }
            }
        },
        "iot_gateway.CameraPlateRequest": {
            "type": "object",
            "required": [
                "gate_id",
                "plate_number"
            ],
            "properties": {
                "gate_id": {
                    "type": "integer"
                },
                "plate_number": {
                    "type": "string"
                }
            }
        },
        "iot_gateway.CameraPlateResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "iot_gateway.RfidScanRequest": {
            "type": "object",
            "required": [
                "gate_id",
                "mac_address",
                "rfid_uid"
            ],
            "properties": {
                "gate_id": {
                    "type": "integer"
                },
                "mac_address": {
                    "type": "string"
                },
                "rfid_uid": {
                    "type": "string"
                }
            }
        },
        "iot_gateway.RfidScanResponse": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "\"open_barrier\" | \"reject\"",
                    "type": "string"
                },
                "lcd_line1": {
                    "description": "VD: \"BS:51A-123.45\"",
                    "type": "string"
                },
                "lcd_line2": {
                    "description": "VD: \"Moi vao!\" hoặc \"Tam biet!\"",
                    "type": "string"
                },
                "message": {
                    "description": "log nội bộ",
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "parking_lot.CreateParkingLotRequest": {
            "type": "object",
            "required": [
                "location",
                "name"
            ],
            "properties": {
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "parking_lot.UpdateParkingLotRequest": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "parking_slot.AdminUpdateParkingSlotRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "$ref": "#/definitions/parking_slot.SlotStatus"
                }
            }
        },
        "parking_slot.ChangeSlotDeviceRequest": {
            "type": "object",
            "required": [
                "device_mac",
                "port_number"
            ],
            "properties": {
                "device_mac": {
                    "type": "string"
                },
                "port_number": {
                    "type": "integer"
                }
            }
        },
        "parking_slot.CreateParkingSlotRequest": {
            "type": "object",
            "required": [
                "device_mac",
                "lot_id",
                "name",
                "port_number"
            ],
            "properties": {
                "device_mac": {
                    "type": "string"
                },
                "lot_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "port_number": {
                    "type": "integer"
                }
            }
        },
        "parking_slot.SensorUpdateParkingSlotRequest": {
            "type": "object",
            "required": [
                "is_occupied",
                "mac",
                "port"
            ],
            "properties": {
                "is_occupied": {
                    "type": "boolean"
                },
                "mac": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                }
            }
        },
        "parking_slot.SlotStatus": {
            "type": "string",
            "enum": [
                "AVAILABLE",
                "OCCUPIED",
                "MAINTAIN"
            ],
            "x-enum-varnames": [
                "SlotStatusAvailable",
                "SlotStatusOccupied",
                "SlotStatusMaintain"
            ]
        },
        "rfid_card.CardType": {
            "type": "string",
            "enum": [
                "REGISTERED",
                "GUEST"
            ],
            "x-enum-varnames": [
                "CardTypeRegistered",
                "CardTypeGuest"
            ]
        },
        "rfid_card.CreateRfidCardRequest": {
            "type": "object",
            "required": [
                "card_type",
                "uid"
            ],
            "properties": {
                "card_type": {
                    "$ref": "#/definitions/rfid_card.CardType"
                },
                "is_active": {
                    "type": "boolean"
                },
                "owner_name": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "rfid_card.UpdateRfidCardRequest": {
            "type": "object",
            "properties": {
                "card_type": {
                    "$ref": "#/definitions/rfid_card.CardType"
                },
                "is_active": {
                    "type": "boolean"
                },
                "owner_name": {
                    "type": "string"
                }
            }
        },
        "user.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "confirm_password",
                "new_password",
                "old_password"
            ],
            "properties": {
                "confirm_password": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 6
                },
                "old_password": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 6
                }
            }
        },
        "user.ChangeRoleRequest": {
            "type": "object",
            "required": [
                "new_role"
            ],
            "properties": {
                "new_role": {
                    "$ref": "#/definitions/user.Role"
                }
            }
        },
        "user.CreateUserRequest": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name",
                "password",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "role": {
                    "$ref": "#/definitions/user.Role"
                }
            }
        },
        "user.Role": {
            "type": "string",
            "enum": [
                "USER",
                "MANAGER",
                "ADMIN"
            ],
            "x-enum-varnames": [
                "RoleUser",
                "RoleManager",
                "RoleAdmin"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Smart Parking Backend API",
	Description:      "Backend API cho hệ thống smart parking",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
